FROM golang:1.20-bullseye

# Set a working directory for the application
WORKDIR /app

# Create a volume to mount your Go code
VOLUME ["/app"]

# Copy your Go source code from the mounted volume
COPY . .

RUN go version
